### ISSUE TITLE
Git commit error

### ISSUE THREAD

**Issue by cdupuis** [atomist-skills/string-replace-skill#38]
https://go.atomist.com/log/T7GMF5USG/bca264f2-ee05-47db-9833-0d43e0714a93/W9VOVrylo8ixV0GEN8mRJ?name=string-replace-skill&namespace=atomist

```
2020-05-02 01:36:49.226 ERROR: promise error:  Error: Child process 36 exited with non-zero status 1: /tmp/atm-1-1CZNMvEIPSIlY ==> git 'commit' '-m' 'Ran string replacement s/([a-zA-Z]*?)_([a-zA-Z])/$1\U$2/g on *.{yaml,yml}
[atomist:edited]'
```

**Comment by cdupuis** [comment]
I think that `git commit` failed because there were no actual changes to commit. Probably that log statement was just confusing for me to see as I thought something failed.

**Comment by slimslenderslacks** [comment]
Yes, there were no changes on the commit.  But the more important point is what lead you to think that something should have happened here I guess.

**Comment by cdupuis** [comment]
I used the pattern `*.{yml,yaml}` which should have matched a couple of files but apparently it didn’t.

**Comment by slimslenderslacks** [comment]
Have migrated to fast-glob - will push this out
